// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOCfxvKQ5Ovh-5A2ZVQhmn_R8mzn4cR5E',
    appId: '1:828932102560:web:04bba5dc662005ec596cc5',
    messagingSenderId: '828932102560',
    projectId: 'kuratracker-ada17',
    authDomain: 'kuratracker-ada17.firebaseapp.com',
    storageBucket: 'kuratracker-ada17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOCfxvKQ5Ovh-5A2ZVQhmn_R8mzn4cR5E',
    appId: '1:828932102560:android:04bba5dc662005ec596cc5',
    messagingSenderId: '828932102560',
    projectId: 'kuratracker-ada17',
    storageBucket: 'kuratracker-ada17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOCfxvKQ5Ovh-5A2ZVQhmn_R8mzn4cR5E',
    appId: '1:828932102560:ios:04bba5dc662005ec596cc5',
    messagingSenderId: '828932102560',
    projectId: 'kuratracker-ada17',
    iosBundleId: 'com.surgicalsupply.woundcarepro',
    storageBucket: 'kuratracker-ada17.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOCfxvKQ5Ovh-5A2ZVQhmn_R8mzn4cR5E',
    appId: '1:828932102560:ios:04bba5dc662005ec596cc5',
    messagingSenderId: '828932102560',
    projectId: 'kuratracker-ada17',
    iosBundleId: 'com.surgicalsupply.woundcarepro',
    storageBucket: 'kuratracker-ada17.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOCfxvKQ5Ovh-5A2ZVQhmn_R8mzn4cR5E',
    appId: '1:828932102560:web:04bba5dc662005ec596cc5',
    messagingSenderId: '828932102560',
    projectId: 'kuratracker-ada17',
    authDomain: 'kuratracker-ada17.firebaseapp.com',
    storageBucket: 'kuratracker-ada17.firebasestorage.app',
  );
}
