// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWebDevelopment123456789',
    appId: '1:112078476646:web:abc123def456',
    messagingSenderId: '112078476646',
    projectId: 'surgical-supply',
    authDomain: 'surgical-supply.firebaseapp.com',
    storageBucket: 'surgical-supply.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForAndroidDevelopment123456',
    appId: '1:112078476646:android:abc123def456',
    messagingSenderId: '112078476646',
    projectId: 'surgical-supply',
    storageBucket: 'surgical-supply.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOSDevelopment123456789',
    appId: '1:112078476646:ios:abc123def456',
    messagingSenderId: '112078476646',
    projectId: 'surgical-supply',
    bundleId: 'com.surgicalsupply.woundcarepro',
    storageBucket: 'surgical-supply.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForMacOSDevelopment123456',
    appId: '1:112078476646:ios:abc123def456',
    messagingSenderId: '112078476646',
    projectId: 'surgical-supply',
    bundleId: 'com.surgicalsupply.woundcarepro',
    storageBucket: 'surgical-supply.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindowsDevelopment123456',
    appId: '1:112078476646:web:abc123def456',
    messagingSenderId: '112078476646',
    projectId: 'surgical-supply',
    authDomain: 'surgical-supply.firebaseapp.com',
    storageBucket: 'surgical-supply.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );
}
